services:
  - type: web
    name: Web-cloner-4
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
